# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jpg2pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 75, 54, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 170, 72, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 84, 16))
        self.label_3.setObjectName("label_3")
        self.pdf_name = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_name.setGeometry(QtCore.QRect(100, 250, 133, 20))
        self.pdf_name.setObjectName("pdf_name")
        self.img_dir_btn = QtWidgets.QPushButton(self.centralwidget)
        self.img_dir_btn.setGeometry(QtCore.QRect(723, 75, 71, 23))
        self.img_dir_btn.setObjectName("img_dir_btn")
        self.pdf_out_btn = QtWidgets.QPushButton(self.centralwidget)
        self.pdf_out_btn.setGeometry(QtCore.QRect(710, 170, 81, 23))
        self.pdf_out_btn.setObjectName("pdf_out_btn")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(10, 320, 75, 23))
        self.start_btn.setObjectName("start_btn")
        self.pdf_out = QtWidgets.QLineEdit(self.centralwidget)
        self.pdf_out.setGeometry(QtCore.QRect(110, 170, 381, 21))
        self.pdf_out.setObjectName("pdf_out")
        self.img_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.img_dir.setGeometry(QtCore.QRect(100, 70, 401, 21))
        self.img_dir.setObjectName("img_dir")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(110, 320, 361, 23))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JPG2PDF"))
        self.label.setText(_translate("MainWindow", "图片目录:"))
        self.label_2.setText(_translate("MainWindow", "PDF输出目录:"))
        self.label_3.setText(_translate("MainWindow", "输出PDF文件名:"))
        self.img_dir_btn.setText(_translate("MainWindow", "图片目录"))
        self.pdf_out_btn.setText(_translate("MainWindow", "PDF输出目录"))
        self.start_btn.setText(_translate("MainWindow", "转换"))
